Permissions tests on all pages for all roles
Z3n1t3ch/zenistock_automation pull request #11
Opened 2022-07-26 09:44 UTC by BiancaJoca

Tests for User:
user is able to perform actions on Device/Employees/Asset/Licenses page (add device, export, import + actions from 3 dots button)
Tests for Admin and Super Admin
Admin/SuperAdmin is able to perform actions on Device/Employees/Asset/Licenses page (add device, export, import + actions from 3 dots button)

2022-07-26 10:06 UTC, DariusChis commented on src/main/java/pageObjects/Permissions.java
> +    private WebElement signInButton;
Could you delete these attributes since they are not used?

2022-07-26 10:21 UTC, CaprarClaudiu requested changes

2022-07-26 10:21 UTC, CaprarClaudiu commented on .gitignore
> +target
add an empty line

2022-07-26 10:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Permissions.java
> +import java.util.concurrent.TimeUnit;
remove any unused imports

2022-07-26 10:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Permissions.java
> +    private WebElement assetsButtonSidebarMenu;
remove any unused web elements

2022-07-26 10:21 UTC, CaprarClaudiu commented on src/test/java/pageObjects/PermissionsTest.java
> +        Assert.assertTrue(true);
this test does not check anything, it will always pass

2022-07-26 10:21 UTC, CaprarClaudiu commented on src/test/java/pageObjects/PermissionsTest.java
> +    }
what are we checking here?

2022-07-26 10:21 UTC, CaprarClaudiu commented on src/test/java/pageObjects/PermissionsTest.java
> +    }
what are we checking here?

2022-07-26 10:21 UTC, CaprarClaudiu commented on src/test/java/pageObjects/PermissionsTest.java
> +}
you could also do 3 checks for all the roles if they can Add a new tag

2022-07-26 10:22 UTC, TarcutaAndrada commented on src/test/java/pageObjects/PermissionsTest.java
> +        Assert.assertTrue(true);
@BiancaJoca change the assert

2022-07-28 08:11 UTC, MihaiScorusZeni approved these changes

2022-07-28 08:59 UTC, TarcutaAndrada approved these changes

2022-07-28 09:11 UTC, CaprarClaudiu approved these changes

2022-07-28 09:14 UTC, merged