Added tests for edit device (it will be updated when warranty functio…
Z3n1t3ch/zenistock_automation pull request #14
Opened 2022-07-29 08:06 UTC by MihaiScorusZeni

…nality will be functional again)

2022-07-29 10:46 UTC, DariusChis commented
Please solve conflicts

2022-07-29 10:51 UTC, DariusChis commented on src/main/java/utils/FilterDevice.java
>          driver.findElement(By.id("filter_device_button")).click();
Update the branch, this class doesn't exist anymore

2022-07-29 10:51 UTC, DariusChis commented on src/test/java/pageObjects/DevicePageTests.java
> +        Assert.assertEquals(successEdit, "Item updated successfully!");
Could you check if the name of the device was updated by adding another assertion?

2022-08-02 07:45 UTC, CaprarClaudiu requested changes

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/test/java/pageObjects/BaseTest.java
> -        employeePage = new EmployeePage(driver);
have we decided we need to remove these objects?

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/test/java/pageObjects/DevicePageTests.java
> +    }
are we sure the item is successfully edited just by having a success message displayed?

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +import org.checkerframework.checker.units.qual.C;
are we using this import?

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +import utils.Constants;
are we using this import?

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +import static utils.Constants.*;
do not use wildcard imports

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
>          signInAsAdmin();
keep the spacing constant in the whole class

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +        nameField.click();
do we need to click on the text field?

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +        serialNoField.click();
do we need to click on the text field?

2022-08-02 07:45 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("error_toaster")));
why do we have a wait for the error message in this test but on the other negative edit tests we dont?

2022-08-02 09:57 UTC, DariusChis reviewed
please delete binary files

2022-08-02 09:57 UTC, DariusChis commented on src/main/java/utils/RandomGenerator.java
> +
This method is always going to return today's date, it's not random. Also, you only use it once in your code and it can be replaced with a constant

2022-08-02 10:35 UTC, DariusChis approved these changes

2022-08-02 12:21 UTC, CaprarClaudiu requested changes

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +import utils.RandomGenerator;
are we using this?

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +        invoiceDateField.click();
:)

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +        startDateWarrantyField.click();
:)

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +        endDateWarrantyField.click();
:)

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +        endDateWarrantyField.click();
:)

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/main/java/utils/RandomGenerator.java
> +import java.util.Date;
are we using these?

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/test/java/pageObjects/BaseTest.java
> +        driverFactory = new DriverFactory(driver);
what is the reasoning behind this driver object?

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/test/java/pageObjects/DevicePageTests.java
> +import driver.DriverFactory;
:)

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/test/java/pageObjects/DevicePageTests.java
> +        Assert.assertTrue(editedDevice.contains(devicePage.getDeviceWarrantyEndDate()));
are these working as expected?

2022-08-02 12:21 UTC, CaprarClaudiu commented on src/main/java/driver/DriverFactory.java
> +
i am not sure all of these work as expected

2022-08-04 06:38 UTC, CaprarClaudiu requested changes
Fix all the previous PR threads and reuse elements in your tests

2022-08-04 06:38 UTC, CaprarClaudiu commented on src/main/java/driver/DriverFactory.java
>      }
is this working as intended? becouse you take the text from the whole table and then return the first element which if im not mistaken should be a text "Name"

2022-08-04 06:38 UTC, CaprarClaudiu commented on src/main/java/utils/Constants.java
> +import java.util.Date;
?

2022-08-04 06:38 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +import org.openqa.selenium.*;
try not to use wildcard imports

2022-08-04 06:38 UTC, CaprarClaudiu commented on src/test/java/pageObjects/DevicePageTests.java
> +import utils.Constants;
?

2022-08-04 06:38 UTC, CaprarClaudiu commented on src/test/java/pageObjects/DevicePageTests.java
> +//    }
you can leave both the test and method uncommented and just comment the @Test annotation so it will not run

2022-08-04 06:38 UTC, CaprarClaudiu commented on src/main/java/pageObjects/DevicePage.java
> +//    } ( will work when it will be repaired)
leave the comment on top of the method and make the message more clear

2022-08-04 12:41 UTC, CaprarClaudiu commented on src/test/java/pageObjects/DevicePageTests.java
> +        String editedDevice =driver.findElement(By.id("device-table")).getText();
?

2022-08-04 13:01 UTC, CaprarClaudiu approved these changes

2022-08-04 13:54 UTC, merged