Create automated tests for device filter
Z3n1t3ch/zenistock_automation pull request #20
Opened 2022-08-04 11:47 UTC by BiancaJoca

ZS2022-34
Create automated tests for device filter

- Filter is working as expected
- Filter is working with multiple fields used
- Clear All button resets the filter fields

2022-08-04 14:13 UTC, DariusChis commented
please solve conflicts

2022-08-04 16:48 UTC, CaprarClaudiu reviewed
Resolve conflicts

2022-08-04 16:48 UTC, CaprarClaudiu commented on src/main/java/driver/DriverFactory.java
> +    public static void signInAsSuperAdmin() {
do we need to change these to static?

2022-08-04 16:48 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Filter.java
> +    public static void filterBySubcategory() {
do we need this to be static?

2022-08-04 16:48 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Filter.java
> +    public static void filterBySubcategoryAndName() {
do we need this to be static?

2022-08-04 16:48 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Filter.java
> +    public static void clearAllButton() {
do we need this to be static? also the name is not very clear (pun intended). could you rename it?

2022-08-04 16:48 UTC, CaprarClaudiu commented on src/test/java/pageObjects/FilterTest.java
> +    }
correct me if im wrong but if we get the text from the whole table, we also get the header which has a column called "Name". this means we will always have this test pass even if the filter is not working as long as the device table loads

2022-08-04 16:48 UTC, CaprarClaudiu commented on src/test/java/pageObjects/FilterTest.java
> +    }
are you sure you are calling the correct method for your test? :)

2022-08-04 16:48 UTC, CaprarClaudiu commented on src/test/java/pageObjects/FilterTest.java
> +        Assert.assertEquals(URL, Constants.DEVICES_URL);
here you have the unused string table. you can either delete it or add a new assert. i suggest that you should rethink this test. try something like this: open filter -> filter by something -> wait for the page to load -> open filter and click clear button -> then open filter again and check if the field is be empty.

2022-08-08 06:21 UTC, CaprarClaudiu requested changes

2022-08-08 06:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Filter.java
> +    WebElement option0;
are we using this webelement? if we do i dont think that is the correct ID

2022-08-08 06:21 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Filter.java
> +    String name = "0";
i think this should be placed in the constants file

2022-08-08 06:21 UTC, CaprarClaudiu commented on src/test/java/pageObjects/FilterTest.java
> +import utils.Constants;
:)

2022-08-08 10:09 UTC, CaprarClaudiu approved these changes

2022-08-08 10:40 UTC, MihaiScorusZeni approved these changes

2022-08-08 10:41 UTC, merged