Refactored employee page.
Z3n1t3ch/zenistock_automation pull request #24
Opened 2022-08-08 11:44 UTC by MihaiScorusZeni

2022-08-08 12:45 UTC, CaprarClaudiu requested changes
There are variables created inside the method, elements can be created/reused and too many wait times.

2022-08-12 12:03 UTC, CaprarClaudiu requested changes

2022-08-12 12:03 UTC, CaprarClaudiu commented on src/main/java/driver/DriverFactory.java
> +        }
this can be done easier using a switch case

2022-08-12 12:03 UTC, CaprarClaudiu commented on src/main/java/pageObjects/EmployeePage.java
> +    WebElement successToaster;
there seem to be some unused web elements

2022-08-12 12:03 UTC, CaprarClaudiu commented on src/main/java/pageObjects/EmployeePage.java
> +    WebElement successToaster;
and imports

2022-08-12 12:03 UTC, CaprarClaudiu commented on src/main/java/driver/DriverFactory.java
> +    private String email;
if we use these strings only for one method, they can be declared in the method

2022-08-12 12:03 UTC, CaprarClaudiu commented on src/test/java/pageObjects/EmployeePageTests.java
> +import static pageObjects.EmployeePage.elementText;
there is an unused import

2022-08-12 12:29 UTC, BiancaJoca approved these changes

2022-08-12 12:52 UTC, CaprarClaudiu approved these changes

2022-08-12 13:00 UTC, merged