Zs2022 42 refactor login page tests
Z3n1t3ch/zenistock_automation pull request #25
Opened 2022-08-08 11:49 UTC by MihaiScorusZeni

2022-08-08 12:37 UTC, CaprarClaudiu requested changes
Are you sure you refactored all the methods and tests related to the login page?

2022-08-08 12:37 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Credentials.java
>      public static final String device_details = "https://zenistock.zenitech.local/device-details";
are these credentials? also the class should not be in this package

2022-08-08 12:37 UTC, CaprarClaudiu commented on src/main/java/pageObjects/LoginPage.java
>          wait.until(ExpectedConditions.urlToBe(Credentials.dashboard));
you can create a wait method and call it using a parameter

2022-08-09 10:55 UTC, BiancaJoca approved these changes

2022-08-09 12:15 UTC, CaprarClaudiu requested changes
Should we also move the Errors class?

2022-08-09 12:15 UTC, CaprarClaudiu commented on src/main/java/utils/Constants.java
> +    public static final String device_details = "https://zenistock.zenitech.local/device-details";
we should have these uppercase since thats the structure we went for the constants class

2022-08-09 12:15 UTC, CaprarClaudiu commented on src/main/java/utils/Credentials.java
> +    public static final String errorInvalidCredentials = "Invalid credentials";
isnt this already in the Errors class? we could call it from there

2022-08-09 12:15 UTC, CaprarClaudiu commented on src/main/java/pageObjects/LoginPage.java
>  import org.openqa.selenium.support.ui.ExpectedConditions;
:)

2022-08-09 12:15 UTC, CaprarClaudiu commented on src/test/java/pageObjects/LoginPageTests.java
>          String URL = driver.getCurrentUrl();
this can be made an helper method

2022-08-09 12:15 UTC, CaprarClaudiu commented on src/test/java/pageObjects/LoginPageTests.java
>          String invalidCredentials = driver.findElement(By.id("password-helper-text")).getText();
this can be made a helper method

2022-08-09 12:15 UTC, CaprarClaudiu commented on src/test/java/pageObjects/LoginPageTests.java
>          boolean errorMessage = driver.getPageSource().contains(hasRequired);
this can be made a helper method

2022-08-11 13:08 UTC, DariusChis approved these changes

2022-08-11 14:18 UTC, CaprarClaudiu approved these changes

2022-08-12 07:03 UTC, merged