ZS2022-44 Refactor TagPage Tests
Z3n1t3ch/zenistock_automation pull request #27
Opened 2022-08-09 11:05 UTC by DariusChis

https://zenitech.atlassian.net/browse/ZS2022-44

2022-08-09 12:26 UTC, BiancaJoca approved these changes

2022-08-09 12:29 UTC, CaprarClaudiu requested changes
Please do not refactor classes that are not necessary for this task (filter , permissions). Also you can do some refactoring to the TagsPageTests class also. (use helper methods, declare webelements to be used in the tests, the getText and required field code can be made helper methods)

2022-08-09 12:29 UTC, CaprarClaudiu commented on src/main/java/driver/DriverFactory.java
> +import org.openqa.selenium.By;
:)

2022-08-09 12:29 UTC, CaprarClaudiu commented on src/main/java/driver/DriverFactory.java
> +    WebElement deviceFilterApplyButton;
do we need to change this to be public?

2022-08-09 12:29 UTC, CaprarClaudiu commented on src/main/java/pageObjects/TagsPage.java
> +    private Permissions permissions;
we should not do this, we should just declare the web elements here also.

2022-08-09 12:29 UTC, CaprarClaudiu commented on src/main/java/pageObjects/TagsPage.java
> +        elementToLoad(devicePage.successToaster);
we should declare the elements in this class. its better than calling them from other classes especially if they are not from a helper class

2022-08-09 12:29 UTC, CaprarClaudiu commented on src/main/java/pageObjects/TagsPage.java
>          driver.findElement(By.id("tags-list-tag-" + name + "-item-delete")).click();
could we use a helper method? and declare an element so we can just click on it

2022-08-09 12:29 UTC, CaprarClaudiu commented on src/main/java/pageObjects/TagsPage.java
>          editField.sendKeys(Keys.DELETE);
this can be made a helper method

2022-08-09 12:29 UTC, CaprarClaudiu commented on src/main/java/pageObjects/TagsPage.java
> +        wait.until(ExpectedConditions.visibilityOf(devicePage.successToaster));
use the helper method

2022-08-09 12:29 UTC, CaprarClaudiu commented on src/main/java/pageObjects/TagsPage.java
> +        devicePage.saveDeviceButton.click();
you could make a helper method for this, or reuse the create device method

2022-08-10 12:37 UTC, MihaiScorusZeni approved these changes

2022-08-10 13:15 UTC, CaprarClaudiu approved these changes

2022-08-10 13:15 UTC, merged