ZS2022-43 Refactored Permissions tests
Z3n1t3ch/zenistock_automation pull request #28
Opened 2022-08-09 12:16 UTC by BiancaJoca

2022-08-09 12:19 UTC, DariusChis approved these changes

2022-08-09 12:34 UTC, CaprarClaudiu commented on src/main/java/pageObjects/Permissions.java
> +        pageToLoad(Constants.TAGS_URL);
these look like duplicates to me, i think we can reuse some of them

2022-08-09 12:34 UTC, CaprarClaudiu requested changes
I think we should also refactor the PermissionsTest class

2022-08-10 12:08 UTC, CaprarClaudiu approved these changes

2022-08-10 12:09 UTC, merged